title: Olivier Le Pestipon # your name (or website title) here
logo: "/assets/images/profil2.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)

  <h2>Hi, I'm Olivier!</h2> 
  <p>A web developer and data analyst who creates accessible and inclusive digital spaces and products.</p>
  <p>Data enthusiast, I have been working in the product devellopment for tech company for many years.</p>
  <p>Whether you're a startup or a Fortune500 company, there is always opportunity to make your product more accessible. </p>
  <p><strong>Let's get in Touch !</strong></p>
  <a href="https://www.linkedin.com/in/olivierlepestipon/">View My LinkedIn</a>
  <br>
  <a href="https://github.com/OlivierLpp">View My Github</a>
  <br>
  <a href="mailto:o.lepestipon@gmail.com">Send me an Email</a>


theme: jekyll-theme-minimal
google_analytics: G-9N0NH8B7DZ # your Google Analytics tracking ID here
